config/routes.rb
Pam::Application.routes.draw do
  resources :departments
  match '/departments/:id/attribute/:attribute(?:hash)' => 'departments#get_attribute'

  resources :groups
  resources :people
  match '/people/:id/attribute/:attribute(?:hash)' => 'people#get_attribute'

  match '/login(/:uid)' => 'user#auth'
  match '/logout' => 'user#logout'

  match '/403', :to => 'home#error_403'
  match "/404", :to => "home#error_404"
  match "/422", :to => "home#error_422"
  match "/500", :to => "home#error_500"

  match '/token/:uid/:token' => 'user#token'

  root :to => 'user#index'

end

app/models/department.rb
class Department < ActiveLdap::Base
  ldap_mapping dn_attribute: "cn",
               prefix: "ou=Departments",
               classes: ["inetOrgPerson"]
  belongs_to :persons, :many => 'o'

  alias groups_mapping persons
  def persons(return_objects=true)
    return groups_mapping if return_objects
    attr = 'cn'
    Person.search(:attribute => 'o',
    :value => id,
    :attributes => [attr]).map {|dn, attrs| attrs[attr]}.flatten
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :init
  def init
    @MENU[:departments][:active] = true
    redirect_to :controller => 'home', :action => 'error_403' if !@USER.member? 'ldapadmin'
  end

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/attribute/sn
  def get_attribute
    person = Department.find(params[:id]);

    mime = "application/octet-stream"

    atr = person.must + person.may
    atr.each { |e|
      if e.name == params[:attribute] then
        case e.syntax.id
        when "1.3.6.1.4.1.1466.115.121.1.28"
          mime = "image/jpeg"
        end
      end
    }
    a = person.attributes[params[:attribute]]
    if a.kind_of?(Array) then a = a[0] end

    if a.nil?  then
      render :status => 404
    else
      send_data a, :type => mime
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    if !params[:upload].nil? then
      params[:upload].each { |n,f|
        params[:department][n] = f.tempfile.read
      }
    end

    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    if !params[:upload].nil? then
      params[:upload].each { |n,f|
        params[:department][n] = f.tempfile.read
      }
    end

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_attribute.html.erb
<dt class="<%= "blank-attribute" if @department.attributes[m.name].nil? and !defined? all%>">
	<acronym title="<%= m.description %>"><%= if m.aliases.count > 0 then m.aliases[0] else m.name end %></acronym>
	<% if m.aliases.count > 0 then %><acronym title="<%= m.name %>">*</acronym> <% end %>
</dt>
<dd  class="<%= "blank-attribute" if @department.attributes[m.name].nil? and !defined? all %>">
	<% case m.syntax.id %>
	<% when "1.3.6.1.4.1.1466.115.121.1.12",
	"1.3.6.1.4.1.1466.115.121.1.15",
	"1.3.6.1.4.1.1466.115.121.1.22",
	"1.3.6.1.4.1.1466.115.121.1.26",
	"1.3.6.1.4.1.1466.115.121.1.36",
	"1.3.6.1.4.1.1466.115.121.1.40",
	"1.3.6.1.4.1.1466.115.121.1.41",
	"1.3.6.1.4.1.1466.115.121.1.44",
	"1.3.6.1.4.1.1466.115.121.1.50",
	"1.3.6.1.4.1.1466.115.121.1.51",
	"1.3.6.1.4.1.1466.115.121.1.52"%>
	<% if @department.attributes[m.name].kind_of?(Array) then %>
		<% if @department.attributes[m.name].count > 1 then %>
			<% @department.attributes[m.name].each {|e| %>
				<input id="department_<%= m.name %>" name="department[<%= m.name %>][]" size="<%= m.syntax.length %>" type="text" value="<%= e %>" />
			<% }%>
		<% else %>
			<input id="department_<%= m.name %>" name="department[<%= m.name %>]" size="<%= m.syntax.length %>" type="text" value="<%= @department.attributes[m.name].first %>" />
		<% end %>
	<% else %>
		<input id="department_<%= m.name %>" name="department[<%= m.name %>]" size="<%= m.syntax.length %>" type="text" value="<%= @department.attributes[m.name] %>" />
	<% end %>
	<% when "1.3.6.1.4.1.1466.115.121.1.27" %>
	<input id="department_<%= m.name %>" name="department[<%= m.name %>]" type="number" value="<%= if @department.attributes[m.name].kind_of?(Array) then @department.attributes[m.name][0] else @department.attributes[m.name] end %>" />
	<% when "1.3.6.1.4.1.1466.115.121.1.28",
	"1.3.6.1.4.1.1466.115.121.1.23" %>
	<% if !@department.attributes[m.name].nil? then %>
	<img src="<%= url_for :id => @department.id, :action => "get_attribute", :attribute => m.name, :hash => Digest::MD5.hexdigest(if @department.attributes[m.name].kind_of?(Array) then @department.attributes[m.name][0] else @department.attributes[m.name] end) %>" alt="<%= m.name %>"/>
	<% end %>
	<input name="upload[<%= m.name %>]" type="file" maxlength="<%= m.syntax.length %>">
	<% else %>
	OID '<%= m.syntax.id %>' (<%= m.syntax.description %>) ist nicht implementiert!
	<pre><%= @department.attributes[m.name] %></pre>																														
	<% end %>
</dd>

app/views/departments/_form.html.erb
<button onclick="show_all_attributes(); return false;">
	Alles Anzeigen
</button>

<%= form_for(@department, :html => {:multipart => true}) do |f| %>
<% if @department.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

	<ul>
		<% @department.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<dl class="dl-horizontal lage-dt">
	<% done_list = {}%>
	<% @department.must.each {|m| %>
	<%= render('attribute', :m => m, :all => true) if done_list[m.id].nil?%>
	<% done_list[m.id] = true }%>

	<% @department.may.each {|m| %>
	<%= render('attribute', :m => m) if done_list[m.id].nil?%>
	<% done_list[m.id] = true }%>
</dl>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/departments/_show.html.erb
<dt class="<%= "blank-attribute" if @department.attributes[m.name].nil? and !defined? all%>">
	<acronym title="<%= m.description %>"><%= if m.aliases.count > 0 then m.aliases[0] else m.name end %></acronym>
	<% if m.aliases.count > 0 then %><acronym title="<%= m.name %>">*</acronym> <% end %>
</dt>
<dd  class="<%= "blank-attribute" if @department.attributes[m.name].nil? and !defined? all %>">
	<% case m.syntax.id %>
	<% when "1.3.6.1.4.1.1466.115.121.1.12",
	"1.3.6.1.4.1.1466.115.121.1.15",
	"1.3.6.1.4.1.1466.115.121.1.22",
	"1.3.6.1.4.1.1466.115.121.1.26",
	"1.3.6.1.4.1.1466.115.121.1.36",
	"1.3.6.1.4.1.1466.115.121.1.40",
	"1.3.6.1.4.1.1466.115.121.1.41",
	"1.3.6.1.4.1.1466.115.121.1.44",
	"1.3.6.1.4.1.1466.115.121.1.50",
	"1.3.6.1.4.1.1466.115.121.1.51",
	"1.3.6.1.4.1.1466.115.121.1.52",
	# Numbers:
	"1.3.6.1.4.1.1466.115.121.1.27"%>
	<% if @department.attributes[m.name].kind_of?(Array) then
	if @department.attributes[m.name].count > 1 then %>
	<ul>
		<% @department.attributes[m.name].each{|e|%>
		<li>
			<%= e%>
		</li>
		<% } %>
	</ul>
	<% else %>
	<%= @department.attributes[m.name][0] %>
	<% end
	else %>
	<%= @department.attributes[m.name] %>
	<% end %>
	<% when "1.3.6.1.4.1.1466.115.121.1.28",
	"1.3.6.1.4.1.1466.115.121.1.23" %>
	<% if !@department.attributes[m.name].nil? then %>
	<img src="<%= url_for :id => @department.id, :action => "get_attribute", :attribute => m.name, :hash => Digest::MD5.hexdigest(if @department.attributes[m.name].kind_of?(Array) then @department.attributes[m.name][0] else @department.attributes[m.name] end) %>" alt="<%= m.name %>"/>
	<% end %>
	<% else %>
	OID '<%= m.syntax.id %>' (<%= m.syntax.description %>) ist unbekannt.
	<pre><%= @department.attributes[m.name] %></pre>																																	
	<% end %>
</dd>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table class="table table-hover">
	<tr>
		<th>CommonName</th>
		<th>Bezeichnung</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @departments.each do |department| %>
	<tr>
		<td><%= department.cn%></td>
		<td><%= department.sn%></td>
		<td><%= link_to 'Show', department %></td>
		<td><%= link_to 'Edit', edit_department_path(department) %></td>
		<td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %>
</table>

<br />

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<dl class="dl-horizontal lage-dt">
	<% done_list = {}%>
	<% @department.must.each {|m| %>
	<%= render('show', :m => m) if done_list[m.id].nil?%>
	<% done_list[m.id] = true }%>

	<% @department.may.each {|m| %>
	<%= render('show', :m => m) if done_list[m.id].nil?%>
	<% done_list[m.id] = true }%>
</dl>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>